blog/urls.py
from django.urls import path

from blog.views import (
    CategoryPostView, CategoryListView, IndexView,
    PostDetailView, SearchPostView, TagListView, TagPostView,
    CommentFormView, comment_approve, comment_remove,
    ReplyFormView, reply_approve, reply_remove, )

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categorise/', CategoryListView.as_view(), name='category_list'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('category/<str:category_slug>/', CategoryPostView.as_view(), name='category_post'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),

]

blog/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    """ Category registration model """
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """ Tag registration model """
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    """ Post entry model """
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)
    image = models.ImageField(
        upload_to='post_images/', null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class ContentImage(models.Model):
    """ Insert images into blog posts """
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']

    def approve(self):
        self.approve = True
        self.save()

    def __str__(self):
        return self.text


class Reply(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='replies')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def approve(self):
        self.approve = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django.forms import ModelForm, TextInput, Textarea

from blog.models import Comment, Reply


class CommentForm(ModelForm):
    class Meta(object):
        model = Comment
        fields = ('author', 'text')
        # bootstrapのform-controlを使用している
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'コメント内容',
            }),
        }
        # Put label name in placeholder
        labels = {
            'author': '',
            'text': '',
        }


class ReplyForm(ModelForm):
    class Meta(object):
        model = Reply
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': '返信内容',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from blog.forms import CommentForm, ReplyForm
from blog.models import Category, Comment, Post, Reply, Tag


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 5


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))


class CategoryPostView(ListView):
    model = Post
    template_name = 'blog/category_post.html'
    paginate_by = 5

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model = Post
    template_name = 'blog/tag_post.html'
    paginate_by = 5

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class SearchPostView(ListView):
    """ Search function """
    model = Post
    template_name = 'blog/search_post.html'
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(category__name__icontains=query) |
                Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context


class CommentFormView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('blog:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        context['post'] = get_object_or_404(Post, pk=post_pk)
        return context


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)


class ReplyFormView(CreateView):
    model = Reply
    form_class = ReplyForm

    def form_valid(self, form):
        reply = form.save(commit=False)
        comment_pk = self.kwargs['pk']
        reply.comment = get_object_or_404(Comment, pk=comment_pk)
        reply.save()
        return redirect('blog:post_detail', pk=reply.comment.post.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        context['comment'] = get_object_or_404(Comment, pk=comment_pk)
        return context


@login_required
def reply_approve(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.approve()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)


@login_required
def reply_remove(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.delete()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)

blog/templates/blog/category_list.html
<h1>カテゴリ一覧</h1>
<ul>
  {% for category in object_list %}
  <li>{{ category.name }} ({{ category.num_posts }})</li>
  {% empty %}
  <li>カテゴリはありません。</li>
  {% endfor %}
</ul>

blog/templates/blog/category_post.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-lg-8">
      <h1 class="mb-4 main-top">「{{ category.name }}」の投稿一覧</h1>
      <!--      {% if user.is_authenticated or post.is_public %}-->
      <p class="text-right">{{ page_obj.start_index }}-{{ page_obj.end_index }}件（{{ paginator.count }}件）</p>
      <!--       {% endif %}-->
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination.html" %}

    </main>
    {% include "blog/snippets/sidebar.html" %}
  </div>
</div>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "base.html" %}

{% block title %}コメント投稿フォーム | {{ block.super }}{% endblock %}
{% block description %}コメント投稿フォームのページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-lg-8">
      <h1 class="mb-4">コメント投稿フォーム</h1>
      <p>To:「{{ post.title }}」</p>
      <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-primary">送信</button>
      </form>
    </main>
    {% include "blog/snippets/sidebar.html" %}
  </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}投稿一覧 | {{ block.super }}{% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-lg-8">
      <h1 class="mb-4 main-top">投稿一覧</h1>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination.html" %}
    </main>
    {% include "blog/snippets/sidebar.html" %}
  </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'blog/css/post_detail.css' %}">
<div class="container">
  <div class="row">
    <main class="col-lg-8">
      {% include "blog/snippets/breadcrumb.html" %}
      <article class="blog-area">
        <h1 class="post-title">{{ object.title }}</h1>
        <hr>
        <ul id="post-data">
          <li><img src="{% static '/blog/img/time.svg' %}"> {{ object.published_at|date }}</li>
          <li>{% for tag in object.tags.all %}
            <a href="{% url 'blog:tag_post' tag.slug %}" class="side-tag">
              #{{ tag.name }}</a>
            {% endfor %}
          </li>
        </ul>
        <div class="has-text-align-center">
          {{ object.content|safe }}
        </div>
      </article>
      <hr id="end-hr">
      <article class="comment-area">
        <a class="btn-sm btn btn-outline-primary" href="{% url 'blog:comment_form' post.pk %}">コメントを投稿する</a>
        {% include "blog/snippets/comments.html" %}
      </article>
    </main>
    {% include "blog/snippets/sidebar.html" %}
  </div>
</div>
{% endblock %}

blog/templates/blog/reply_form.html
{% extends "base.html" %}

{% block title %}コメント返信フォーム | {{ block.super }}{% endblock %}
{% block description %}コメント返信フォームのページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-lg-8">
      <h1 class="mb-4">コメント返信フォーム</h1>
      <p>To: {{ comment.author }}さん</p>
      <p class="text-black-50">{{ comment.text|linebreaksbr }}</p>
      <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">送信</button>
      </form>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/search_post.html
{% extends "base.html" %}

{% block title %}{% if query %}{{ query }}{% endif %} | {{ block.super }}{% endblock %}
{% block description %}検索ワード「{% if query %}{{ query }}{% endif %}」での検索結果ページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-lg-8">
      <h1 class="mb-4">「{% if query %}{{ query }}{% endif %}」の検索結果</h1>
      <p class="text-right">{{ page_obj.start_index }}-{{ page_obj.end_index }}件（{{ paginator.count }}件）</p>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination.html" %}
    </main>
    {% include "blog/snippets/sidebar.html" %}
  </div>
</div>
{% endblock %}

blog/templates/blog/tag_list.html
<h1>タグ一覧</h1>
<ul>
  {% for tag in object_list %}
  <li>{{ tag.name }} ({{ tag.num_posts }})</li>
  {% empty %}
  <li>タグはありません。</li>
  {% endfor %}
</ul>

blog/templates/blog/tag_post.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-lg-8">
      {% include "blog/snippets/breadcrumb.html" %}
      <h1 class="mb-4 main-top">「#{{ tag.name }}」の投稿一覧</h1>
      <p class="text-right">{{ page_obj.start_index }}-{{ page_obj.end_index }}件（{{ paginator.count }}件）</p>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination.html" %}
    </main>
    {% include "blog/snippets/sidebar.html" %}
  </div>
</div>
{% endblock %}